// flow-typed signature: 0a6a965c2989f96eef2a47702c89dd02
// flow-typed version: <<STUB>>/group-by_v^0.0.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'group-by'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'group-by' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'group-by/index' {
  declare module.exports: $Exports<'group-by'>;
}
declare module 'group-by/index.js' {
  declare module.exports: $Exports<'group-by'>;
}
