// flow-typed signature: e5fbc9c3b384c86dabc9e1e2f973e12b
// flow-typed version: <<STUB>>/is-dom_v^1.0.9/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'is-dom/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'is-dom/index' {
  declare module.exports: $Exports<'is-dom'>;
}
declare module 'is-dom/index.js' {
  declare module.exports: $Exports<'is-dom'>;
}
declare module 'is-dom/test.js' {
  declare module.exports: $Exports<'is-dom/test'>;
}
